### ISSUE TITLE
Code updating?

### ISSUE THREAD

**Issue by ghost** [zhao-ht/GIMLET#2]
Hi, thank you for sharing and maintaining your great work!
It seems like the codes are updated.
Is there any change we should care when constructing the environment required to reproduce your work?
I wonder the current update might change the required versions of the required modules.

Thank you:)

**Comment by zhao-ht** [comment]
Thank you for your interest in our project!

In this update, we have made enhancements without altering the environment requirements. 

Specifically, we've integrated data and model loading methods from Hugging Face, along with pipeline support for these features. These additions make working with our dataset and model much more convenient and flexible, ultimately enhancing your research experience. We hope you find these improvements beneficial! If you have any further questions or feedback, feel free to share. Happy researching!

**Comment by ghost** [comment]
Hi @zhao-ht 
Thank you for your kind reply!
I understand you have updated the utility of your work for our better experience.
I will try it again, and might ask another question about your code.
Thank you for your continuous support. It is a great help for our interest in your work:)
Sincerely.
