### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by AkanshDivker** [zhao-ht/GIMLET#3]
Hi,

I couldn't find any licensing information for the repository. Is the use and modification of GIMLET prohibited?

Thanks!

**Comment by zhao-ht** [comment]
Thank you for taking an interest in our project! 

You're welcome to use and modify our project. If you utilize our code, data, or model, please kindly cite our paper. We've added licenses to our data and model on HuggingFace. We'll be adding the license file shortly. Appreciate the reminder!
